BEGIN;

CREATE TABLE IF NOT EXISTS kazika_studio_agents.scene_layouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_story_scene_id BIGINT NOT NULL REFERENCES kazika_studio_agents.story_scenes_domain(id) ON DELETE CASCADE,
  source_story_scene_id BIGINT REFERENCES kazikastudio.story_scenes(id) ON DELETE SET NULL,
  asset_id BIGINT REFERENCES kazika_studio_agents.assets(id) ON DELETE SET NULL,
  version INTEGER NOT NULL DEFAULT 1,
  title TEXT NOT NULL DEFAULT 'キャラクター配置図',
  layout_kind TEXT NOT NULL DEFAULT 'character_blocking',
  description TEXT,
  spatial_notes TEXT,
  characters JSONB NOT NULL DEFAULT '[]'::jsonb,
  anchors JSONB NOT NULL DEFAULT '[]'::jsonb,
  props JSONB NOT NULL DEFAULT '[]'::jsonb,
  constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(agent_story_scene_id, version)
);

COMMENT ON TABLE kazika_studio_agents.scene_layouts IS 'Scene-level character blocking / placement diagrams used as spatial references for image/video generation. Camera position is intentionally excluded; shot prompts decide camera work.';
COMMENT ON COLUMN kazika_studio_agents.scene_layouts.asset_id IS 'Optional rendered layout diagram asset, usually kazika_studio_agents.assets.asset_type = layout_reference.';
COMMENT ON COLUMN kazika_studio_agents.scene_layouts.characters IS 'Structured character placement: character id/name, role, area, posture/action, facing, relation notes.';
COMMENT ON COLUMN kazika_studio_agents.scene_layouts.anchors IS 'Environment anchors such as desks, blackboard, windows, doors, stage zones; no camera anchors.';
COMMENT ON COLUMN kazika_studio_agents.scene_layouts.constraints IS 'Generation guidance, e.g. use layout only for relative spatial relationships; character sheets override appearance; shot prompts override framing.';

CREATE INDEX IF NOT EXISTS ksa_scene_layouts_scene_idx
  ON kazika_studio_agents.scene_layouts(agent_story_scene_id, version DESC);
CREATE INDEX IF NOT EXISTS ksa_scene_layouts_asset_idx
  ON kazika_studio_agents.scene_layouts(asset_id);
CREATE INDEX IF NOT EXISTS ksa_scene_layouts_active_idx
  ON kazika_studio_agents.scene_layouts(agent_story_scene_id)
  WHERE is_active;
CREATE UNIQUE INDEX IF NOT EXISTS ksa_scene_layouts_one_active_idx
  ON kazika_studio_agents.scene_layouts(agent_story_scene_id)
  WHERE is_active;

COMMIT;
